site_name: BestPrep Docs
site_url: https://bestprep.github.io/Docs/

nav:
  - Home:
    - Start Here: index.md
    - Add a Page: add_page.md
  - Understanding Salesforce: 
    - How It Works: systems.md
    - Salesforce Contacts: contacts.md
  - Board Portal:
    - Overview: board/overview.md
    - Content: board/content.md
    - Access Control: board/access.md
  - Mentoring:
      - Overview: mentoring/mentoring.md
      - Reports: mentoring/reports.md
      - Portals:
          - Mentor Portal:
              - Overview: mentoring/mentor_portal/mentor_portal.md
              - Apex: mentoring/mentor_portal/mentor_apex.md
              - JavaScript: mentoring/mentor_portal/mentor_js.md
              - HTML & CSS: mentoring/mentor_portal/mentor_web.md
          - Student Portal:
              - Overview: mentoring/student_portal/student_portal.md
              - Apex: mentoring/student_portal/student_apex.md
              - JavaScript: mentoring/student_portal/student_js.md
              - HTML & CSS: mentoring/student_portal/student_web.md
          - Overview Portal:
              - Overview: mentoring/overview_portal/overview_portal.md
              - Apex: mentoring/overview_portal/overview_apex.md
              - JavaScript: mentoring/overview_portal/overview_js.md
              - HTML & CSS: mentoring/overview_portal/overview_web.md
      - Systems:
          - Flagging System:
              - Overview: mentoring/flagging_system/flagging_system.md
              - Making Updates: mentoring/flagging_system/making_updates.md
          - Email System:
              - Notifications: mentoring/email_system/notification_email.md
              - Email Templates: mentoring/email_system/email_templates.md
          - Other Systems:
              - Other Flows: mentoring/other_systems/other_flows.md
              - Portal Upload: mentoring/other_systems/portal_upload.md
              - Overdue App: mentoring/other_systems/overdue_app.md
  - Student Spotlight:
    - Overview: student_spotlight/overview.md
    - Yearly Setup: student_spotlight/setup.md
    - Experience Site: student_spotlight/site.md
    - Teacher Pre-Reg: student_spotlight/prereg.md
    - Student Submission: student_spotlight/submission.md
    - Judge Sign-Up: student_spotlight/judge-signup.md
    - Judging Portal: student_spotlight/judge-portal.md
  - Forms:
    - Overview: forms/forms.md
  - Flows:
    - Overview: flows/flows.md

theme:
  name: material
  logo: images/footer-logo.png
  favicon: images/favicon.ico
  features:
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: orange
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

docs_dir: content
site_dir: docs

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://bestprep.org
      name: BestPrep Website
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/BestPrepMN
      name: BestPrep's Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/bestprep/
      name: BestPrep's LinkedIn
    - icon: fontawesome/brands/github
      link: https://www.github.com/bestprep
      name: BestPrep's GitHub
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/bestprep
      name: BestPrep's Facebook

plugins:
  - search
  
markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - md_in_html


extra_css:
  - css/custom.css

extra_javascript:
  - https://unpkg.com/mermaid@10.9.3/dist/mermaid.min.js
  - js/mermaid-init.js
  - js/clickable.js
